name: "💻 Sematic Release"

on:
  push:
    branches:
      - master
    tags:
      v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v3
      - name: 🟢 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📦 Install Dependencies
        run: yarn
      - name: 📦 Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release